### ISSUE TITLE
May I ask why there is no training code

### ISSUE THREAD

**Issue by zhengxiuguang123** [cv-stuttgart/CCMR#3]

**Comment by Harsh188** [comment]
Agreed.

**Comment by az-ja** [comment]
@zhengxiuguang123 
I will add the code for training as soon as I find some spare time.

**Comment by az-ja** [comment]
@zhengxiuguang123 @Harsh188 

I added the training code: 4b0ec1ad0eed1847e17e755f883c102211a1caaf.
