### ISSUE TITLE
Could you provide the checkpoints trained on Chairs and Things?

### ISSUE THREAD

**Issue by ZhonghuaYi** [cv-stuttgart/CCMR#5]
I notice that some optical flow works (e.g., RAFT and GMA) provide the checkpoint after training on Chairs and Things. And I'm interest with the performance of the model only trained on Chairs (CCMR-chairs and CCMR+_things) and fine-tuned version on Things (CCMR-things and CCMR+_things).

Although they could be obtained by following the training setting, it requires large computation cost and disk storage. So I wonder if it's convinent to provide these four checkpoints (CCMR-chairs, CCMR-things, CCMR+_chairs, CCMR+_things)?

**Comment by az-ja** [comment]
Hello,

I released those checkpoints [here](https://github.com/cv-stuttgart/CCMR/releases).

**Comment by az-ja** [comment]
Hello,

I released those checkpoints [here](https://github.com/cv-stuttgart/CCMR/releases).
